"""Repository protocols for testability. Implementations in repositories/."""
from typing import Any, Optional, Protocol


class ProductRepository(Protocol):
    """Protocol for product persistence."""

    async def get_by_id(self, product_id: str, columns: Optional[str] = None, conn: Any = None) -> Optional[dict]: ...
    async def insert(self, product_dict: dict, conn: Any = None) -> None: ...
    async def update(self, product_id: str, updates: dict, conn: Any = None) -> Optional[dict]: ...
    async def delete(self, product_id: str, conn: Any = None) -> int: ...
    async def find_by_original_sku_and_vendor(self, original_sku: str, vendor_id: str) -> Optional[dict]: ...


class DepartmentRepository(Protocol):
    """Protocol for department persistence."""

    async def get_by_id(self, dept_id: str) -> Optional[dict]: ...
    async def get_by_code(self, code: str) -> Optional[dict]: ...
    async def list_all(self) -> list: ...
    async def increment_product_count(self, dept_id: str, delta: int, conn: Any = None) -> None: ...


class VendorRepository(Protocol):
    """Protocol for vendor persistence."""

    async def get_by_id(self, vendor_id: str) -> Optional[dict]: ...
    async def find_by_name(self, name: str) -> Optional[dict]: ...
    async def increment_product_count(self, vendor_id: str, delta: int, conn: Any = None) -> None: ...
